### ISSUE TITLE
Tracking issue for chalk

### ISSUE THREAD

**Issue by jackh726** [rust-lang/types-team#25]
A non-comprehensive list of high-impact changes to be made or current differences to be addressed to align with rustc:
- [ ] `Param` removal in rustc or addition in Chalk
- [ ] Late-bound region handling
- [x] Tracking bound vars
- [x] Variance/subtyping
- [ ] Placeholder canonicalization
- [ ] rustc considers `BoundVars` to be WF, Chalk doesn't 

TODO: fill in more later

**Comment by compiler-errors** [comment]
This should be closed as chalk is removed from the compiler, I think
